version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - tox-env-{{ checksum "requirements/default.txt" }}-{{ checksum "requirements/test.txt" }}
            # fallback to using the latest cache if no exact match is found
            - tox-env-

      - run:
          name: create venv
          command: |
            python3 -m venv ../venv

      - run:
          name: install tox
          command: |
            . ../venv/bin/activate
            pip install -U pip
            pip install --upgrade pip setuptools
            pip install tox

      - save_cache:
          paths:
            - ../.tox
          key: tox-env-{{ checksum "requirements/default.txt" }}-{{ checksum "requirements/test.txt" }}

      - run:
          name: build project
          command: |
            . ../venv/bin/activate
            tox --workdir ../.tox

      - run:
          name: coverage report
          command: |
            python3 -m venv ../venv
            . ../venv/bin/activate
            pip install codecov
            codecov